### ISSUE TITLE
failing on windows?

### ISSUE THREAD

**Issue by narimiran** [status-im/nim-chronos#21] opened 2019-03-08 14:40 UTC
Based on [Nim appveyor tests](https://ci.appveyor.com/project/Araq/nim/builds/22904093/job/h2hm7t0hb3owy9g1/tests), this package fails on Windows.

I don't have Windows so I cannot reproduce, but I have been told that running `nim c tests/teststream.nim` produces `..\chronos\transports\stream.nim(287, 27) Error: 'writeStreamLoop' is not GC-safe as it performs an indirect call here`/

This is likely connected to https://github.com/nim-lang/Nim/commit/c86b1fbcac11520380ad15e103a8ec429228d735 and could probably be fixed on your end by some extra `{.gcsafe.}` at some places.

**Comment by cheatfate** [comment] 2019-03-09 19:05
Sorry but this is not Chronos bug, but new bug of Nim compiler. This function do not touch any global values which are in GC memory.

Until @Araq will not explain new `gcsafe` behavior properly in documentation or specification this issue will be closed.

**Comment by zah** [comment] 2019-03-09 19:15
@cheatfate, the issue is that the code makes a call through a function pointer, which is not marked with `gcsafe`. The function pointer type is this one:
https://github.com/status-im/nim-chronos/blob/9f15c6b7528de313e3d8b3a1fecd81f66998ab20/chronos/asyncloop.nim#L243

Since the pointer is not `gcsafe`, in theory it's possible that a non-gcsafe function is assigned to it, so the compiler has to make the conservative assumption that the caller of the pointer (writeStreamLoop) may not be gcsafe as well.

**Comment by cheatfate** [comment] 2019-03-11 01:12
@zah https://github.com/nim-lang/RFCs/issues/142

**Closed** 2019-03-26 12:29 UTC
