### ISSUE TITLE
nim doc doesn't work with nim-chronos

### ISSUE THREAD

**Issue by Menduist** [status-im/nim-chronos#229] opened 2021-10-28 09:52 UTC
It seems that `asyncdispatch` had a lot of `when defined(nimdoc):` to allow the generation of documentation,
but this has been lost in chronos, and `nim doc chronos.nim` completely fails.

Is this fixable? Since `nim doc` compiles everything, we can't use `nim doc` on libp2p as long as chronos doesn't work (and still exposes the right procs)

**Comment by arnetheduck** [comment] 2021-11-08 14:18
Duplicate of https://github.com/status-im/nim-chronos/issues/186

**Closed by arnetheduck** 2021-11-08 14:18 UTC
