### ISSUE TITLE
Chronos fails with `IndexError` in NBC

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-chronos#115] opened 2020-08-04 22:04 UTC
When running NBC against Medalla I'm getting the following on or shortly after startup:

```
.../nim-beacon-chain/vendor/nim-testutils/testutils/moduletests.nim(21) beacon_node
.../nim-beacon-chain/beacon_chain/beacon_node.nim(1198) main
.../beacon_chain/beacon_node.nim(892) start
.../beacon_chain/beacon_node.nim(842) run
.../vendor/nim-chronos/chronos/asyncloop.nim(278) poll
.../vendor/nim-chronos/chronos/transports/stream.nim(1329) readStreamLoop
.../vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: index 4096 not in 0 .. 4095 [IndexError]
```

OS: `Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64`

**Comment by cheatfate** [comment] 2020-09-09 14:07
I was able to constantly reproduce this error with incorrect arguments, in this particular case `readExactly()` with `nbytes < 0` could cause this problem.
In `chronos` we can only add check for arguments, but its impossible to fix on this side.
https://github.com/status-im/nim-chronos/pull/128.

**Comment by dryajov** [comment] 2020-09-09 14:58
> I was able to constantly reproduce this error with incorrect arguments, in this particular case `readExactly()` with `nbytes < 0` could cause this problem.
> In `chronos` we can only add check for arguments, but its impossible to fix on this side.
> #128.

That makes sense, #128 should allows us to at least catch all the places where this might be happening.

**Comment by cheatfate** [comment] 2020-09-23 15:21
I'm closing it because there no reports on an issue anymore, so maybe it was fixed not only in `chronos` but in `nim-libp2p` too.

**Closed by cheatfate** 2020-09-23 15:21 UTC
